spring.application.name=catalogo
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
# Puerto y bind para Docker/Cloud
server.port=8090
server.address=0.0.0.0

# Evitar error de DataSource en ejecución local sin BD
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
